In [16]:
import pandas as pd
df = pd.read_excel('Plan Description.xlsx')
df.head(15)

,Plan ID,Plan Name,Payer name,Payer Channel
0,22913263,DEAN FOCUS BRONZE (WI),DEAN HEALTH PLAN (WI),COMMERCIAL
1,7904103,DEAN FOCUS BRONZE HSA (WI),DEAN HEALTH PLAN (WI),COMMERCIAL
2,22845031,DEAN FOCUS SILVER HSA (WI),DEAN HEALTH PLAN (WI),COMMERCIAL
3,6799059,DEAN FOCUS SILVER (WI),DEAN HEALTH PLAN (WI),COMMERCIAL
4,6527249,PREVEA360 PLATINUM PLUS (WI),DEAN HEALTH PLAN (WI),COMMERCIAL
5,11875598,PREVEA360 GOLD CLASSIC (WI),DEAN HEALTH PLAN (WI),COMMERCIAL
6,6789342,PREVEA360 GOLD VALUE (WI),DEAN HEALTH PLAN (WI),COMMERCIAL
7,10432255,PREVEA360 GOLD HSA (WI),DEAN HEALTH PLAN (WI),COMMERCIAL
8,17581392,PREVEA360 SILVER HSA (WI),DEAN HEALTH PLAN (WI),COMMERCIAL
9,6808306,DEAN HEALTH PLAN HIX GNRL,DEAN HEALTH PLAN (WI),COMMERCIAL
10,6790902,DEAN HEALTH PLAN HIX EPO GNRL,DEAN HEALTH PLAN (WI),COMMERCIAL
11,6809373,DEAN HEALTH PLAN HIX HMO GNRL,DEAN HEALTH PLAN (WI),COMMERCIAL
12,6795080,DEAN HEALTH PLAN PPO (WI),DEAN HEALTH PLAN (WI),COMMERCIAL
13,6811174,DEAN FOCUS GOLD (WI),DEAN HEALTH PLAN (WI),COMMERCIAL
14,10025287,DEAN BRONZE PLUS (WI),DEAN HEALTH PLAN (WI),COMMERCIAL

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4544 entries, 0 to 4543
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Plan ID        4544 non-null   int64
 1   Plan Name      4544 non-null   object
 2   Payer name     4544 non-null   object
 3   Payer Channel  4544 non-null   object
dtypes: int64(1), object(3)
memory usage: 142.1+ KB

In [34]:
df1 = df[df['Payer Channel']=='COMMERCIAL']
df1.shape

(2940, 4)

In [35]:
Top_Payers = df1['Payer name'].value_counts().to_frame()
Top_Payers.head()

                                  Payer name
AETNA INC                                498
COVENTRY HEALTH CARE/FIRST HLTH          328
HEALTH NET INC                           137
UNITED HEALTHCARE                        133
BCBS ANTHEM/WELLPOINT/WELLCHOICE         101

In [33]:
df2.shape

(2940, 4)

In [37]:
Top_Payers.rename(columns={'Payer name':'Count'})

                                  Count
AETNA INC                           498
COVENTRY HEALTH CARE/FIRST HLTH     328
HEALTH NET INC                      137
UNITED HEALTHCARE                   133
BCBS ANTHEM/WELLPOINT/WELLCHOICE    101
...                                 ...
PPOM (MI)                             1
CAROLINA RETAIL CLERKS FOOD EMP.      1
PHARM PROVIDERS OF OK UNSPEC          1
TRINITY HEALTH PLANS                  1
MCLAREN HEALTH PLAN (MI)              1

[253 rows x 1 columns]

In [39]:
Top_Payers.to_csv('Top_Payers.csv')